apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultra-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ultra-api
  template:
    metadata:
      labels:
        app: ultra-api
    spec:
      containers:
      - name: api
        image: ultra-api:latest
        ports:
        - containerPort: 5000
